import { StrictMode } from "react";

import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { RouterProvider } from "@tanstack/react-router";
import { routeTree } from "../routeTree.gen"; // auto-generated by TanStack Router
import { createRouter } from "@tanstack/react-router";

const queryClient = new QueryClient();

// Create router instance
const router = createRouter({ routeTree });

// Required for type-safety
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

export const App = () => (
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
);
