services:
  # ----------------------------------------------------------------
  # DATABASES
  # ----------------------------------------------------------------
  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    ports:
      - "5433:5432" # external:internal
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - app-network

  post-db:
    image: mongo:6
    container_name: post-db
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Tools
  # ----------------------------------------------------------------

  pgadmin:
    image: dpage/pgadmin4
    container_name: my-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    depends_on: [auth-db]
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro  # pre-load servers
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

  # ----------------------------------------------------------------
  # Services
  # ----------------------------------------------------------------
  auth:
    build: ./services/auth
    env_file: .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${AUTH_DATABASE_URL}
    depends_on: [auth-db]
    ports:
      - "4001:4001"
    networks:
      - app-network

  post:
    build: ./services/post
    env_file: .env
    environment:
      POSTS_DATABASE_URL: ${POST_SERVICE_URL}
    depends_on: [post-db]
    ports:
      - "4003:4003"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4003"]
      interval: 30s
      timeout: 10s
      retries: 5
  gateway:
    build: ./gateway
    depends_on:
      post:
        condition: service_healthy
    ports:
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  auth_data:
  mongodata:
  pgadmin_data:
