version: "3.9"

services:
  # ------------------------------
  # Databases
  # ------------------------------
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  post-db:
    image: mongo:7
    container_name: post-db
    volumes:
      - post-db-data:/data/db
    ports:
      - "27017:27017"

  connections-db:
    image: neo4j:5.10
    container_name: connections-db
    environment:
      # Default username/password combo: neo4j / test
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # optional tuning
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=512m
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - connections-db-data:/data





  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - user-db

# ------------------------------
# Persistent volumes
# ------------------------------
volumes:
  user-db-data:
  post-db-data:
  connections-db-data:
